apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomather{{ if .Values.meta.dev }}-dev{{ end }}
spec:
  selector:
    matchLabels:
      app: gomather{{ if .Values.meta.dev }}-dev{{ end }}
  template:
    metadata:
      labels:
        app: gomather{{ if .Values.meta.dev }}-dev{{ end }}
    spec:
      containers:
        - name: gomather{{ if .Values.meta.dev }}-dev{{ end }}
          image: {{ .Values.meta.image }}
          {{ if not .Values.meta.dev }}
          resources:
            limits:
              memory: {{ .Values.resources.memory }}
              cpu: {{ .Values.resources.cpu }}
          {{ end }}
          ports:
            - containerPort: 30000
  {{ if .Values.meta.dev }}

---
apiVersion: v1
kind: Service
metadata:
  name: gomather-dev
spec:
  selector:
    app: gomather-dev
  type: NodePort
  ports:
    - name: grpc
      port: 30000
      targetPort: 30000
      nodePort: {{ .Values.ingress.nodePort }}
  {{ else }}

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gomather
spec:
  selector:
    app: gomather
  maxReplicas: {{ .Values.resources.maxReplicas }}
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gomather
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60

---
apiVersion: v1
kind: Service
metadata:
  name: gomather
spec:
  selector:
    app: gomather
  ports:
    - name: grpc
      port: 30000
      targetPort: 30000

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gomather
  annotations:
    ingress.kubernetes.io/protocol: h2c
spec:
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: gomather
              servicePort: grpc
  {{ end }}
