sudo: required
language: go
dist: bionic
go:
        - "1.13"
addons:
        apt:
                update: true

before_install:
        - go get -u github.com/magefile/mage
        - PLATFORM=linux ARCHITECTURE=amd64 mage protocInstallDependencies
        - mage protocBuild
script:
        - PLATFORM=linux ARCHITECTURE=arm64 mage binaryBuild
        - PLATFORM=linux ARCHITECTURE=amd64 mage binaryBuild
        - PLATFORM=darwin ARCHITECTURE=amd64 mage binaryBuild

deploy:
        skip_cleanup: true
        provider: releases
        file:
                - gomather-server-linux-arm64
                - gomather-server-linux-amd64
                - gomather-server-darwin-amd64
        api_key:
                secure: RqtM19aG+o/sFRvLiLa1ARd1/0Bm0WhRzpOXy3PqnAUbg+KpFjPH9sIXqnxZ4r3195PRDqWzBIL9dJDGd9HOnVs3xJ2N0DKEzeDlcQ88i3KLYklAghliRTkN7TbW3h8RuhsA6oYeTaJIuVz2hTeTITn1FTEwlVzfrJeU6YDZvZ6WKiYImyqeW1AoW1YBNAayETlf+YpxEpUQ+2AX4nEurH6ye1wwil+t3YoI2jJvhzy4AvVn+4riv2V+nuQpQcGPpJuu7Nl3KOmTic8SrFx3OFpxkpJ5/BeybEwAdm8V1W6JkxfBTu5dRYx6ho7ilb65uqtMIJ/Nhdde4l48FPUzlDaGudQ+EjofPQxPreX5yxCtOul08Q5o90+sB0Ro691FNS7AEwyPs3p2mu0LE1cT8DFUzdl5H3ydyC1l53kVdDjuSErGHZJBlIG/Upeb8xlba61Q5q225hXn0xy0kDdxsxnJpDzI0R2nBTFyaaEnSsv+huUcb/cNc7GGcFO49O7IXIHmxbX+6P6VP9peVc0ChNSDD6itYtP4TD80mVCfCluuwNjyccRscJ8txRlu3V8BZezrv20Hna8vXtCFMu8J6GXkdYr2mEGB4RzMSKxPglPz0Q96YiGbLB6bENc6zv1vmfiiKHpUzBF5S/glvGZaLMYKYOwzFMa12DhS8LUarqQ=
        on:
                repo: pojntfx/gomather
                all_branches: true
