sudo: required
language: go
dist: bionic
go:
        - "1.13"
addons:
        apt:
                update: true

before_install:
        - go get -u github.com/magefile/mage
        - PLATFORM=linux ARCHITECTURE=amd64 mage protocInstallDependencies
        - mage protocBuild
script:
        - PLATFORM=linux ARCHITECTURE=arm64 mage binaryBuild
        - PLATFORM=linux ARCHITECTURE=amd64 mage binaryBuild
        - PLATFORM=darwin ARCHITECTURE=amd64 mage binaryBuild

deploy:
        skip_cleanup: true
        provider: releases
        file:
                - grpc-go-math-server-linux-arm64
                - grpc-go-math-server-linux-amd64
                - grpc-go-math-server-darwin-amd64
        api_key:
                secure: WOMVvRgA0SHSr6qRnhm2o+qEnrFvK0G1eNLyn8TwEKPuGekd9w2f29cw7axvddquDsE0WdExShao/Efi31KUMVHJ2oOjqc9iN3IRLFuS40CTVnq93885H55q7GiQLwJlxn98DXVCgkWOiam339YuDmA4UI+WCTKVuvRnXHSLQ+1WC4p0p65lU23kIEH3s+d7wNPZa/SlnoM2N7wCWKTLwMEiRQIGyzy2EeS269icApkp7qU221cFf8RXcAVOP8mV1jg5hYeRid125sTHxoGkMOXjQ8bkSucNH2MMFVPRO8SLwn9cC9DvQXmIYlhvg+9VuZERVaoEJculEmQ2hHvajsYLLTb3TjVIQS5g/ClgEN76o8sUQaWHY1SbRu2tKclrUKO87ilXUxhltbvv0UF4eOARkfwMGpX7JEOi+rpA0s9+0GjmGGPEA31D8OO57iGp2bUTiKihVyERIcgrtPMpFp6p141qftw95lqCxzoUi9j8WCAgZ5jSf9ISKckvOgGs1wKCnuYwC6MzLgCgiaeQS/rvtOQqgvoQVWz9Awg+ZW7nIE71LK+M7X4hhJx37UyohleyExXHiuvMY0ahgYU2FKN550zxgbQFjohO+JV1QJ64DUD/rwo9097nkO4b1Gd3b6rwxRubYVFU/czGzR/FXccYAU9VaxMAuuAKed6Aoro=
        on:
                repo: pojntfx/grpc-go-math
