# Setup env
FROM arm64v8/golang:1.13.4-buster AS build
WORKDIR /app
RUN go get -u github.com/magefile/mage
ENV GO111MODULE=on
ENV PLATFORM=linux
ENV ARCHITECTURE=arm64
COPY ./go.mod ./go.sum ./
RUN go mod download
COPY ./magefile.go ./
RUN mage protocDependencyInstall

# Add app
COPY ./src ./src
COPY ./cmd ./cmd

# Start unit tests, start server and restart both if source changed
EXPOSE 30000
CMD ["mage", "dev"]
