# syntax=docker/dockerfile:experimental
FROM --platform=$TARGETPLATFORM golang
ARG TARGET
ARG TARGETPLATFORM

WORKDIR /app

RUN apt update
RUN apt install -y protobuf-compiler

RUN curl -Lo /tmp/dibs https://github.com/pojntfx/dibs/releases/latest/download/dibs-linux-amd64
RUN install /tmp/dibs /usr/local/bin

ENV GO111MODULE=on

RUN go get github.com/golang/protobuf/protoc-gen-go
RUN go get github.com/go-delve/delve/cmd/dlv

ADD . .

RUN dibs -generateSources
# To reduce build time, automatic sources generation has also been disabled. To generate sources manually, just save
# any file not synced by Skaffold (like a `.proto` file) and the command above will be re-run.
CMD dibs -dev -skipGenerateSources
