apiVersion: skaffold/v1
kind: Config
metadata:
  name: gomather
profiles:
  - name: gomather
    build:
      artifacts:
        - image: pojntfx/gomather
          context: .
          docker:
            dockerfile: Dockerfile
      local:
        useBuildkit: true
    deploy:
      helm:
        releases:
          - name: gomather
            chartPath: charts/gomather
            values:
              meta.image: pojntfx/gomather
  - name: gomather-dev
    build:
      artifacts:
        - image: pojntfx/gomather-dev
          context: .
          docker:
            dockerfile: Dockerfile.dev
          sync:
            infer:
              - "**/*.go"
      local:
        useBuildkit: true
    deploy:
      helm:
        releases:
          - name: gomather-dev
            chartPath: charts/gomather
            values:
              meta.image: pojntfx/gomather-dev
            setValues:
              meta.dev: true
            setValueTemplates:
              meta.target: "{{ .TARGET }}"
              meta.platform: "{{ .TARGETPLATFORM }}"
