apiVersion: v1
name: gomather
version: 0.0.3
description: Simple Go gRPC microservice that does math.
type: application
home: https://pojntfx.github.io/gomather/
sources:
  - git@github.com:pojntfx/gomather.git
maintainers:
  - name: Felix Pojtinger
    email: felix@pojtinger.com
    url: https://felix.pojtinger.com
appVersion: 0.0.3
