meta:
  image: pojntfx/gomather:latest
  dev: false
  debugPort: 31441
  debugNodePort: 31441
  target: "{{ .TARGET }}"
  platform: "{{ .TARGETPLATFORM }}"
  debug: "{{ .DEBUG }}"

resources:
  memory: "128Mi"
  cpu: "512m"
  maxReplicas: 10

ingress:
  nodePort: 30050
  domain: gomather.felicitas.pojtinger.com
  path: /
