meta:
        image: pojntfx/gomather:latest
        dev: false

resources:
        memory: "128Mi"
        cpu: "512m"
        maxReplicas: 10

ingress:
        nodePort: 30050
        domain: gomather.felicitas.pojtinger.space
        path: /
