meta:
  image: pojntfx/gomather:latest
  dev: false
  debug: true
  debugPort: 31441
  debugNodePort: 31441

resources:
  memory: "128Mi"
  cpu: "512m"
  maxReplicas: 10

ingress:
  nodePort: 30050
  domain: gomather.felicitas.pojtinger.com
  path: /
